### ISSUE TITLE
error using @observer with ts 2.6.0-rc in strict mode

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-react#349]
```
Error:(13, 1) TS1238:Unable to resolve signature of class decorator when called as an expression.
  Type 'ClassicComponentClass<CharacterNameProps>' is not assignable to type 'typeof CharacterName'.
    Type 'ClassicComponent<CharacterNameProps, ComponentState>' is not assignable to type 'CharacterName'.
      Types of property 'render' are incompatible.
        Type '() => string | number | false | Element | Element[] | ReactPortal | null' is not assignable to type '() => Element'.
          Type 'string | number | false | Element | Element[] | ReactPortal | null' is not assignable to type 'Element'.
            Type 'null' is not assignable to type 'Element'.
```
I think it is due to this new strict change:
https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#strict-function-types

PS: Im using react 16, but it used to work ok with TS 2.5.3

**Comment by mattoni** [comment]
Having the same issue, it's happening with my @inject calls too.

![image](https://user-images.githubusercontent.com/5110855/32261526-5961edfa-be8c-11e7-890a-9499ddba440b.png)

**Comment by janaagaard75** [comment]
Setting `strictFunctionTypes` to `false` removes the error, confirming @xaviergonz's suspicions.

**Comment by lvpro** [comment]
Also hitting this problem.  Can confirm @janaagaard75 's fix works.

**Comment by KnisterPeter** [comment]
Same here, but I add that setting `strictFunctionTypes` to false is not a good solution.

**Comment by univerio** [comment]
You can also write

```
render(): JSX.Element | false | null {
    ...
}
```

to work around the error, but it does seem a little annoying to have to write that for every component.

**Comment by mattoni** [comment]
@univerio if only i didn't have 500+ components :'(

**Comment by mweststrate** [comment]
Will release a fix later today!

**Comment by mweststrate** [comment]
Should be fixed in `4.3.4`

**Comment by mattoni** [comment]
@mweststrate still having an issue with @inject:

![image](https://user-images.githubusercontent.com/5110855/32349001-e7d2183e-bfd2-11e7-875c-edd2719bb943.png)

is resulting in this error:
![image](https://user-images.githubusercontent.com/5110855/32349038-00c52b06-bfd3-11e7-9362-49c52ec2b3c4.png)

This worked before upgrading to TS 2.6

**Comment by TotallWAR** [comment]
Same here. Any solution?

**Comment by FredyC** [comment]
Please, refrain from commenting on old and closed issues as only a few people will see that. Open new issue with all necessary details. Thank you.
