### ISSUE TITLE
Can't find variable: Symbol

### ISSUE THREAD

**Issue by KakarN** [mobxjs/mobx-react#498]
I am trying to integrate mobx/mobx-react into my react-native project. But I was stuck when I tried to import Provider into the main App.js.

I have this error:

`Error: "Can't find variable: Symbol Evaluating module://mobx-react.js Evaluating module://App.js Loading module://App.js" in`

On further checking I found that the latest version of the mobx/mobx-react was the problem. When I installed the old version, the error was gone.

You can check the latest mobx/mobx-react version [snack here](https://snack.expo.io/@kakarn/mobx---latest-verstion), which does not work.

And the old version of mobx/mobx-react version of [snack here](https://snack.expo.io/@kakarn/mobx---old-version), which does work.

**Comment by mweststrate** [comment]
Fixed in #499 and released as 5.2.2

**Comment by KakarN** [comment]
@mweststrate I am sorry, but I think it's not fixed yet. I have tried with the updated release version ("5.2.2"), but I am still getting the same error:

`Error: "Can't find variable: Symbol Evaluating module://mobx.js Evaluating module://mobx-react.js Evaluating module://App.js Loading module://App.js" in`

You can check the updated release version's [snack here](https://snack.expo.io/@kakarn/mobx-react-updated-version).

**Comment by MrCreeper1008** [comment]
Same issue here with `react-native@0.55.4` with `mobx@5.0.0` and `mobx-react@5.2.2`. Downgraded mobx to `4.3.1` and mobx-react to `5.1.0` fixed the issue for me.

**Comment by mweststrate** [comment]
Should be fixed in 5.2.3

**Comment by sasurau4** [comment]
Thank you for fixing!
But same issue here with `react-native@0.54.4`, `mobx@5.0.0` and `mobx-react@5.2.3` on Android emulator.
Turning on `Debug JS Remotely` fixed the issue for me.
[snack here](https://snack.expo.io/@sasurau4/mobx-react-updated-version)

**Comment by mweststrate** [comment]
MobX 5 doesn't work on RN Android, unless you upgrade  your JavaScriptCore
(See
https://github.com/react-community/jsc-android-buildscripts#how-to-use-it-with-my-react-native-app).
The default one is from 2014  (!!) and doesn't support any modern features
and MobX 5 won't be compatible, use 4 instead

Op ma 11 jun. 2018 om 11:22 schreef Daiki Ihara <notifications@github.com>:

**Comment by sasurau4** [comment]
Oh I didn't know The default JavaScriptCore on Android is so old!!!
Think about upgrading jscore or using MobX v4 instead of v5.

Thanks!

**Comment by juanamd** [comment]
@mweststrate What you mention is really interesting; didn't know about RN and jsc.
I've tried your solution though, but it mentions that it requires a min sdk version of 21 for it to work. Is there any workaround to keep min version 16 while also being able to upgrade to mobx to v5.0+?

**Comment by mweststrate** [comment]
I have no clue about SDKs or something. I think that question is better
asked at the repo that I linked to

Op vr 15 jun. 2018 om 01:57 schreef Juan <notifications@github.com>:

**Comment by z0nekill** [comment]
Just followed the instructions that @mweststrate put together.. worked a treat!
cheers mate!

`mobx: ^5.0.3`
`mobx-react: ^5.2.3`
`react-native: 0.55.4`

Heads up as others are saying - the change requires setting the minimum android SDK version to 21. Otherwise you're looking at downgrading 👎

**Comment by hvaoc** [comment]
Followed these steps based on @mweststrate 's response to fix this

Source: https://github.com/react-community/jsc-android-buildscripts#how-to-use-it-with-my-react-native-app

1. `npm / yarn install jsc-android -D` as dev dependency

2. Make changes to android gradle files 

**android/build.gradle**
```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            url 'https://maven.google.com'
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
           // ADDED THIS - Local Maven repo containing AARs with JSC library built for Android
           url "$rootDir/../node_modules/jsc-android/dist" 
        }
    }
}
```

**android/app/build.gradle**

```
android {
   ...
   defaultConfig {
      minSdkVersion 21
   }
   ...
}

configurations.all {
    resolutionStrategy {
        force 'org.webkit:android-jsc:r224109'
    }
}

dependencies {
   ...
    compile 'org.webkit:android-jsc:r174650'    // ADDED THIS
   ...
}
```

**Comment by himelnagrana** [comment]
@hvaoc - following your steps - i faced this error 
`Could not find org.webkit:android-jsc:r224109.`
while running ``react-native run-android``.

Can you please suggest possibly what have I done wrong?

**Comment by tokinonagare** [comment]
@hvaoc Thanks too much : ) you save my life.

**Comment by pstanton** [comment]
update to @tusharmutreja 's fine post:
	"mobx": "^4.5.0",
	"mobx-react": "^5.2.8",

works a treat.

**Comment by JeffGuKang** [comment]
@pstanton 
It works well on React-Native 0.57.

**Comment by JeffGuKang** [comment]
> update to @tusharmutreja 's fine post:
> "mobx": "^4.5.0",
> "mobx-react": "^5.2.8",
> 
> works a treat.

 It works well on React-Native 0.57.

**Comment by donghuazh** [comment]
Same issue here with react-native@0.57.5 with mobx@5.6.0 and mobx-react@5.3.6.
Downgrading mobx to 4.3.1 or [upgrade  your JavaScriptCore](https://github.com/react-community/jsc-android-buildscripts#how-to-use-it-with-my-react-native-app).

That all works well on React-Native 0.57.5.

**Comment by shuiRong** [comment]
It's my setting:
devDependencies
```
...
"@babel/plugin-proposal-decorators": "^7.2.2",
"metro-react-native-babel-preset": "0.50.0",
"babel-preset-mobx": "^2.0.0",
"jsc-android": "^236355.1.1",
 "mobx": "^5.8.0",
"mobx-react": "^5.4.3",
...
```

.babelrc
```
{
  "presets": ["module:metro-react-native-babel-preset","mobx"],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }]
  ]
}
```

**and upgrade [JavaScript Core](https://github.com/react-community/jsc-android-buildscripts#how-to-use-it-with-my-react-native-app)**

**Comment by TyLy83** [comment]
Thank shuiRong, 
Your solution work for me.

**Comment by sanguineman91** [comment]
差评

**Comment by liri321** [comment]
@hvaoc is declaring **minSdkVersion 21**, in **android/app/build.gradle** really necessary?

**Comment by igor90007** [comment]
"mobx": "4.9.2",
"mobx-react": "5.4.3",
"react-native": "0.58.6",
works good

**Comment by mweststrate** [comment]
Locking conversation, too many random comments that don't add anything to the conversation. Please open a new issue if still running into trouble not solved by what has been mentioned before already
